### ISSUE TITLE
Missing: block_volume_attachement → display_name

### ISSUE THREAD

**Issue by cosmindev** [oracle-terraform-modules/terraform-oci-compute-instance#27]

**Comment by kral2** [comment]
`oci_core_volume_attachment.display_name` is [not updatable](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_volume_attachment#display_name) and not directly exposed to the user.

- providing no information let's the system generate a value type `volumeattachement<timestamp>` that can be queried if needed, but attachment id is probably more usefull
- updating the display_name triggers a force_replace.

Current decision is to not expose this argument to the module user.

If a valid use case is identified, we may revise this decision.
