### ISSUE TITLE
Error compartment_id this field cannot be set

### ISSUE THREAD

**Issue by pnmice** [oracle-terraform-modules/terraform-oci-compute-instance#32]
$terraform init
Initializing modules...
Initializing the backend...
Initializing provider plugins...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
* provider.oci: version = "~> 3.46"
Terraform has been successfully initialized!

$terraform plan
Error: "compartment_id": this field cannot be set
  on .terraform/modules/instance/oracle-terraform-modules-terraform-oci-compute-instance-4c2b22e/main.tf line 71, in resource "oci_core_volume_attachment" "this":
  71: resource "oci_core_volume_attachment" "this" {

$terraform --version
Terraform v0.12.10
+ provider.oci v3.46.0

**Comment by kral2** [comment]
This will be addressed with the TF0.12 upgrade project. Relates to issue #36
