### ISSUE TITLE
Error: data.oci_core_subnet.this: Provider doesn't support data source: oci_core_subnet

### ISSUE THREAD

**Issue by bsmahara** [oracle-terraform-modules/terraform-oci-compute-instance#34]
Hi,

When terraform plan is executed then the below error comes 

 ****Error: data.oci_core_subnet.this: Provider doesn't support data source: oci_core_subnet****

Please help resolve this .

Thanks,
Bhabani

**Comment by bsmahara** [comment]
updated to Terraform v0.13.5 and dont see this issue but seems main.tf is to be changed and i get the below warning . Can someone share  the edited main.tf .

The below needs to be changed
count     = "${length(var.subnet_ocids)}"
 subnet_id = "${element(var.subnet_ocids, count.index)}"
as i get the below warning :
Could you please help ?

**Comment by bsmahara** [comment]
![image](https://user-images.githubusercontent.com/68991376/98112597-79c24780-1ec8-11eb-8395-54cdd9d88584.png)

**Comment by kral2** [comment]
This is related to the new HCL syntax introduced with TF0.12. It will be fixed  with the syntax update project, relates to issue #36

**Comment by aorcl** [comment]
@kral2 can we close this one now?
