### ISSUE TITLE
add additional checks for instance ssh key conditional

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-compute-instance#70]
_From discussion Originally posted by @calorbeer in https://github.com/oracle-terraform-modules/terraform-oci-compute-instance/issues/67#issuecomment-916263890_

There is an issue with `ssh_public_key` variables having default value set to `null`.

If `var.ssh_public_key` value is set by the user, `ssh_authorized_keys` argument is set correctly however if it's `null` the condition is also evaluated to `true` and as a result it is set to `null`.  The file statements are never reached. To avoid this the variables either need to default to "" or the conditions have to test for != null and "".

To do:
- [x] test should be done uppon `null` and we also initialize relavant variables to `null`
- [x] rename `ssh_public_key_path` to `ssh_public_keys_file` (plural form for `keys` and mention `file` explicitely)

**Comment by kral2** [comment]
@calorbeer Would you be volunteer to fix that? :-)

**Comment by kral2** [comment]
I suggest that the test should be done uppon `null` and we also initialize relavant variables to `null`.

`""` is an empty string: that would make the connection impossible, but it becomes a deliberate choice from the module user.

Let's keep the conditional as simple as possible.

**Comment by calorbeer** [comment]
Yes to check for null should be sufficient.

**Comment by kral2** [comment]
Based on [a review comment](https://github.com/oracle-terraform-modules/terraform-oci-compute-instance/pull/71#discussion_r705845730) that appeared in PR #71, we should also adapt the variable names to be semantically correct: using plural form.

rename `ssh_public_key_path` to `ssh_public_keys_path`

For `ssh_public_key`, we need to figure out if there is possibility to pass multiple ssh keys as string or array of strings.

**Comment by kral2** [comment]
Sometimes, less is more :-)

All the use cases can be handled by only one variable: `ssh_public_keys`.

This greatly simplify the code in the module.

```
  metadata = {
    ssh_authorized_keys = var.ssh_public_keys != null ? var.ssh_public_keys : file(var.ssh_authorized_keys)
    user_data           = var.user_data
  }
```

The conditional is here only for backward compatibility with `var.ssh_authorized_keys`. As soon as we move to the next major release, we can drop the conditional all together.
